schema_version: 1

context:
  version: "0.2.0"
  python_min: "3.12"

package:
  name: sen4cap-client
  version: ${{ version }}

source:
  url: https://github.com/Sen4CAP/sen4cap-client/archive/v${{ version }}.tar.gz
  sha256: c437d0fe8c75cfeee47a92bf19bf65adad1ad66dbfdc3b6275abb469de64e04b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sen4cap-client = sen4cap_client.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatch
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - httpx
    - pydantic
    - pydantic-settings
    - pystac
    - pyyaml
    - rasterio
    - rioxarray
    - typer
    - uri-template
    - xarray
    - cuiman >=0.3.1
    - gavicore >=0.3.0

tests:
  - python:
      imports:
        - sen4cap_client
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - sen4cap-client --help

about:
  summary: Python client for the ESA Sen4CAP project
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/Sen4CAP/sen4cap-client

extra:
  recipe-maintainers:
    - TonioF
    - thomasstorm
    - TejasMorbagal
    - konstntokas
    - forman
    - clarasb
    - b-yogesh
    - AliceBalfanz
    - pont-us
